prompt Importing table OPENDAYS...
set feedback off
set define off

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (1, 100, 25, 5, '9:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (2, 150, 14, 7, '15:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (3, 100, 1, 4, '12:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (4, 75, 5, 8, '11:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (5, 80, 4, 7, '16:30');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (6, 200, 22, 3, '21:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (7, 250, 21, 6, '12:30');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (8, 250, 13, 12, '13:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (9, 100, 4, 9, '14:00');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (10, 80, 29, 11, '15:30');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (11, 200, 16, 9, '12');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (13, 200, 29, 4, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (14, 75, 14, 1, '12');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (15, 80, 13, 5, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (16, 100, 20, 3, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (17, 100, 1, 1, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (18, 75, 22, 1, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (19, 75, 1, 1, '15');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (20, 150, 8, 6, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (21, 150, 22, 9, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (22, 150, 21, 8, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (23, 250, 27, 6, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (24, 250, 27, 4, '15');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (25, 100, 17, 2, '12');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (26, 100, 28, 9, '11');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (27, 100, 3, 3, '17');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (28, 75, 13, 12, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (29, 250, 13, 10, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (30, 75, 28, 3, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (31, 80, 26, 6, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (32, 200, 26, 1, '16');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (33, 150, 24, 9, '17');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (34, 200, 13, 1, '11');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (35, 150, 11, 12, '11');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (36, 100, 13, 10, '21');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (37, 100, 22, 9, '16');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (38, 250, 17, 1, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (39, 100, 5, 1, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (40, 250, 28, 10, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (41, 250, 7, 11, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (42, 250, 31, 2, '9');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (43, 150, 11, 6, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (44, 150, 23, 12, '14');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (45, 150, 16, 11, '19');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (46, 150, 6, 10, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (47, 80, 20, 7, '12');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (48, 200, 6, 6, '10');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (49, 150, 28, 10, '10');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (50, 75, 18, 4, '16');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (51, 80, 20, 11, '16');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (52, 100, 18, 10, '11');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (53, 150, 10, 1, '15');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (54, 100, 21, 9, '10');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (55, 150, 2, 3, '15');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (56, 100, 15, 6, '16');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (57, 150, 7, 2, '13');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (58, 250, 11, 9, '18');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (59, 80, 23, 10, '15');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (60, 80, 27, 2, '17');

insert into OPENDAYS (OPENDAYID, NUMPARTICIPANTS, O_DAY, O_MONTH, O_HOUR)
values (12, 75, 7, 11, '20');

prompt Done.
